version: '3'
services:
  database:
    image: postgres:15
    restart: always
    env_file:
      - docker/postgresql/db.env
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgresql/db-data:/var/lib/postgresql/data
      - ./docker/postgresql/db-init:/docker-entrypoint-initdb.d