#!/bin/bash
set -e

echo -n "[*] Creating database '${APP_DATABASE_NAME}'..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE ${APP_DATABASE_NAME};
    \connect ${APP_DATABASE_NAME};
	CREATE SCHEMA IF NOT EXISTS ${APP_DATABASE_SCHEMA};
EOSQL

echo -n "[*] Creating user '${FLYWAY_USER}'..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DATABASE_NAME" <<-EOSQL
    CREATE USER ${FLYWAY_USER} WITH ENCRYPTED PASSWORD '${FLYWAY_PASSWORD}';
    
    GRANT ALL ON SCHEMA ${APP_DATABASE_SCHEMA} TO ${FLYWAY_USER};
    GRANT ALL ON ALL SEQUENCES IN SCHEMA ${APP_DATABASE_SCHEMA} TO ${FLYWAY_USER};

EOSQL

echo -n "[*] Creating user '${APP_USER}'..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DATABASE_NAME" <<-EOSQL
    CREATE USER ${APP_USER} WITH ENCRYPTED PASSWORD '${APP_PASSWORD}';

    GRANT USAGE ON SCHEMA ${APP_DATABASE_SCHEMA} TO ${APP_USER};
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ${APP_DATABASE_SCHEMA} TO ${APP_USER};

    ALTER DEFAULT PRIVILEGES IN SCHEMA ${APP_DATABASE_SCHEMA} 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};

EOSQL




